package com.github.unqUi.model

import kotlin.random.Random

private val random = Random(123)

private fun getRandomIndexes(amount: Int, maxNumber: Int = 100): List<Int> {
    return (0 until maxNumber).shuffled(random).take(amount)
}

private val reviewsText = listOf<String>(
    "For some unfathomable reason, the response team didn't consider a lack of milk for my cereal as a proper emergency.",
    "I want a giraffe, but I'm a turtle eating waffles.",
    "It doesn't sound like that will ever be on my travel list.",
    "Cursive writing is the best way to build a race track.",
    "That must be the tenth time I've been arrested for selling deep-fried cigars.",
    "The crowd yells and screams for more memes.",
    "Lucifer was surprised at the amount of life at Death Valley.",
    "The Japanese yen for commerce is still well-known.",
    "Happiness can be found in the depths of chocolate pudding.",
    "Nobody questions who built the pyramids in Mexico.",
    "He was so preoccupied with whether or not he could that he failed to stop to consider if he should.",
    "Henry couldn't decide if he was an auto mechanic or a priest.",
    "She can live her life however she wants as long as she listens to what I have to say.",
    "She had some amazing news to share but nobody to share it with.",
    "He colored deep space a soft yellow."
)

fun getRottenTomatoesSystem(): RottenTomatoesSystem {
    val rottenTomatoesSystem = RottenTomatoesSystem()
    addCategories(rottenTomatoesSystem)
    addMovies(rottenTomatoesSystem)
    addRelatedMovies(rottenTomatoesSystem)
    addUsers(rottenTomatoesSystem)
    addReview(rottenTomatoesSystem)
    return rottenTomatoesSystem
}

// Categories

private fun addCategories(rottenTomatoesSystem: RottenTomatoesSystem) {
    rottenTomatoesSystem.addCategory(DraftCategory("Action"))
    rottenTomatoesSystem.addCategory(DraftCategory("Adventure"))
    rottenTomatoesSystem.addCategory(DraftCategory("Animation"))
    rottenTomatoesSystem.addCategory(DraftCategory("Comedy"))
    rottenTomatoesSystem.addCategory(DraftCategory("Crime"))
    rottenTomatoesSystem.addCategory(DraftCategory("Documentary"))
    rottenTomatoesSystem.addCategory(DraftCategory("Drama"))
    rottenTomatoesSystem.addCategory(DraftCategory("Family"))
    rottenTomatoesSystem.addCategory(DraftCategory("Fantasy"))
    rottenTomatoesSystem.addCategory(DraftCategory("History"))
    rottenTomatoesSystem.addCategory(DraftCategory("Horror"))
    rottenTomatoesSystem.addCategory(DraftCategory("Music"))
    rottenTomatoesSystem.addCategory(DraftCategory("Mystery"))
    rottenTomatoesSystem.addCategory(DraftCategory("Romance"))
    rottenTomatoesSystem.addCategory(DraftCategory("Science Fiction"))
    rottenTomatoesSystem.addCategory(DraftCategory("TV Movie"))
    rottenTomatoesSystem.addCategory(DraftCategory("Thriller"))
    rottenTomatoesSystem.addCategory(DraftCategory("War"))
    rottenTomatoesSystem.addCategory(DraftCategory("Western"))
}

// Movies

private fun addMovies(rottenTomatoesSystem: RottenTomatoesSystem) {
    getMoviesData().map { rottenTomatoesSystem.addMovie(getDraftMovie(rottenTomatoesSystem, it)) }
}

private class MovieData(val title:String, val description:String, val poster:String, val categories: List<String>)

private fun getMoviesData(): List<MovieData> {
    return listOf(
        MovieData("Turning Red", "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.", "https://image.tmdb.org/t/p/w500/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg", listOf("Animation","Family","Comedy","Fantasy")),
        MovieData("Spider-Man: No Way Home", "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.", "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg", listOf("Action","Adventure","Science Fiction")),
        MovieData("The Adam Project", "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.", "https://image.tmdb.org/t/p/w500/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg", listOf("Action","Adventure","Comedy","Science Fiction")),
        MovieData("Blacklight", "Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.", "https://image.tmdb.org/t/p/w500/7gFo1PEbe1CoSgNTnjCGdZbw0zP.jpg", listOf("Action","Thriller")),
        MovieData("The Batman", "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.", "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg", listOf("Crime","Mystery","Thriller")),
        MovieData("Encanto", "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional familys last hope.", "https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg", listOf("Animation","Comedy","Family","Fantasy")),
        MovieData("No Exit", "Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.", "https://image.tmdb.org/t/p/w500/5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg", listOf("Horror","Thriller")),
        MovieData("Gold", "In the not-too-distant future, two drifters traveling through the desert stumble across the biggest gold nugget ever found and the dream of immense wealth and greed takes hold. They hatch a plan to excavate their bounty, with one man leaving to secure the necessary tools while the other remains with the gold. The man who remains must endure harsh desert elements, ravenous wild dogs, and mysterious intruders, while battling the sinking suspicion that he has been abandoned to his fate.", "https://image.tmdb.org/t/p/w500/ejXBuNLvK4kZ7YcqeKqUWnCxdJq.jpg", listOf("Thriller","Action")),
        MovieData("Pils Adventures", "Pil, a little vagabond girl, lives on the streets of the medieval city of Roc-en-Brume, along with her three tame weasels. She survives of food stolen from the castle of the sinister Regent Tristain. One day, to escape his guards, Pil disguises herself as a princess. Thus she embarks upon a mad, delirious adventure, together with Crobar, a big clumsy guard who thinks shes a noble, and Rigolin, a young crackpot jester. Pil is going to have to save Roland, rightful heir to the throne under the curse of a spell. This adventure will turn the entire kingdom upside down, and teach Pil that nobility can be found in all of us.", "https://image.tmdb.org/t/p/w500/xy6wQ09rMIN2FfWPHJXCWyRZ3P9.jpg", listOf("Adventure","Animation","Comedy","Family","Fantasy")),
        MovieData("Red Notice", "An Interpol-issued Red Notice is a global alert to hunt and capture the worlds most wanted. But when a daring heist brings together the FBIs top profiler and two rival criminals, theres no telling what will happen.", "https://image.tmdb.org/t/p/w500/wdE6ewaKZHr62bLqCn7A2DiGShm.jpg", listOf("Action","Comedy","Crime","Thriller")),
        MovieData("Restless", "After going to extremes to cover up an accident, a corrupt cops life spirals out of control when he starts receiving threats from a mysterious witness.", "https://image.tmdb.org/t/p/w500/9MP21x0OPv0R72obd63tMHssmGt.jpg", listOf("Action","Thriller","Crime")),
        MovieData("Hotel Transylvania: Transformania", "When Van Helsings mysterious invention, the Monsterfication Ray, goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before its too late, and before they drive each other crazy.", "https://image.tmdb.org/t/p/w500/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg", listOf("Animation","Family","Fantasy","Comedy","Adventure")),
        MovieData("The Kings Man", "As a collection of historys worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.", "https://image.tmdb.org/t/p/w500/aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg", listOf("Action","Adventure","Thriller","War")),
        MovieData("My Hero Academia: World Heroes Mission", "A mysterious group called Humarize strongly believes in the Quirk Singularity Doomsday theory which states that when quirks get mixed further in with future generations, that power will bring forth the end of humanity. In order to save everyone, the Pro-Heroes around the world ask UA Academy heroes-in-training to assist them and form a world-classic selected hero team. It is up to the heroes to save the world and the future of heroes in what is the most dangerous crisis to take place yet in My Hero Academia.", "https://image.tmdb.org/t/p/w500/4NUzcKtYPKkfTwKsLjwNt8nRIXV.jpg", listOf("Animation","Action","Fantasy","Adventure")),
        MovieData("The Ice Age Adventures of Buck Wild", "The fearless one-eyed weasel Buck teams up with mischievous possum brothers Crash & Eddie as they head off on a new adventure into Bucks home: The Dinosaur World.", "https://image.tmdb.org/t/p/w500/zzXFM4FKDG7l1ufrAkwQYv2xvnh.jpg", listOf("Animation","Comedy","Adventure","Family")),
        MovieData("Kimi", "A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.", "https://image.tmdb.org/t/p/w500/okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg", listOf("Thriller")),
        MovieData("Eternals", "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.", "https://image.tmdb.org/t/p/w500/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg", listOf("Science Fiction")),
        MovieData("Desperate Riders", "After Kansas Red rescues young Billy from a card-game shootout, the boy asks Red for help protecting his family from the outlaw Thorn, who’s just kidnapped Billy’s mother, Carol. As Red and Billy ride off to rescue Carol, they run into beautiful, tough-as-nails Leslie, who’s managed to escape Thorn’s men. The three race to stop Thorn’s wedding to Carol with guns a-blazing - but does she want to be rescued?", "https://image.tmdb.org/t/p/w500/7pYYGm1dWZGkbJuhcuaHD6nE6k7.jpg", listOf("Western","Action")),
        MovieData("The Commando", "An elite DEA agent returns home after a failed mission when his family makes an unexpected discovery in their house – a stash of money worth $3 million. They soon face the danger and threat of a newly released criminal and his crew, who will do whatever it takes to retrieve the money, including kidnap the agent’s daughters. Stakes are high and lives are at risk in this head-to-head battle as the agent stops at nothing to protect his family against the money-hungry criminals.", "https://image.tmdb.org/t/p/w500/mn1GYIQ1tvFuuu0YBNZBvrHyrkO.jpg", listOf("Action","Crime","Thriller")),
        MovieData("Sing 2", "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.", "https://image.tmdb.org/t/p/w500/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg", listOf("Animation","Comedy","Family","Music")),
        MovieData("Fistful of Vengeance", "A revenge mission becomes a fight to save the world from an ancient threat when superpowered assassin Kai tracks a killer to Bangkok.", "https://image.tmdb.org/t/p/w500/3cccEF9QZgV9bLWyupJO41HSrOV.jpg", listOf("Action","Crime","Fantasy")),
        MovieData("The Requin", "A couple on a romantic getaway find themselves stranded at sea when a tropical storm sweeps away their villa. In order to survive, they are forced to fight the elements, while sharks circle below.", "https://image.tmdb.org/t/p/w500/i0z8g2VRZP3dhVvvSMilbOZMKqR.jpg", listOf("Thriller")),
        MovieData("Venom: Let There Be Carnage", "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.", "https://image.tmdb.org/t/p/w500/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg", listOf("Science Fiction","Action","Adventure")),
        MovieData("Scream", "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.", "https://image.tmdb.org/t/p/w500/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg", listOf("Horror","Mystery","Thriller")),
        MovieData("Nightmare Alley", "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.", "https://image.tmdb.org/t/p/w500/vfn1feL0V9HNSXuLLpaxAW8O6LO.jpg", listOf("Crime","Drama","Thriller")),
        MovieData("The Jack in the Box: Awakening", "When a vintage Jack-in-the-box is opened by a dying woman, she enters into a deal with the demon within that would see her illness cured in return for helping it claim six innocent victims.", "https://image.tmdb.org/t/p/w500/3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg", listOf("Horror")),
        MovieData("Run & Gun", "After leaving a life of crime and violence, Ray is a reformed good guy, enjoying a quiet family life in the ‘burbs. But when his past is discovered, Ray is blackmailed into one last job to collect a mysterious package. After a deadly double-cross, he finds himself wounded and on the run from ruthless assassins who will stop at nothing to get what he has. Now, with the lives of his loved ones hanging in the balance and danger at every turn, Ray’s only hope is to draw upon his violent past to survive.", "https://image.tmdb.org/t/p/w500/h0AKLEk4XCajdav1hSHIR71cU66.jpg", listOf("Action","Thriller")),
        MovieData("Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train", "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boars head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!", "https://image.tmdb.org/t/p/w500/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg", listOf("Animation","Action","Adventure","Fantasy")),
        MovieData("Last Man Down", "After civilization succumbs to a deadly pandemic and his wife is murdered, a special forces soldier abandons his duty and becomes a hermit in the Nordic wilderness. Years later, a wounded woman appears on his doorstep. Shes escaped from a lab and her pursuers believe her blood is the key to a worldwide cure. Hes hesitant to get involved, but all doubts are cast aside when he discovers her pursuer is none other than Commander Stone, the man that murdered his wife some years ago.", "https://image.tmdb.org/t/p/w500/4B7liCxNCZIZGONmAMkCnxVlZQV.jpg", listOf("Action","Thriller")),
        MovieData("Resident Evil: Welcome to Raccoon City", "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.", "https://image.tmdb.org/t/p/w500/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg", listOf("Horror","Action","Science Fiction")),
        MovieData("Looop Lapeta", "When her boyfriend loses a mobsters cash, Savi races against the clock to save the day — if only she can break out of a curious cycle of dead ends.", "https://image.tmdb.org/t/p/w500/onGdT8sYi89drvSJyEJnft97rOq.jpg", listOf("Action","Comedy","Crime")),
        MovieData("The Bad Guys", "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.", "https://image.tmdb.org/t/p/w500/1s0em1CVrM1e6fsafiNePXqh6Hv.jpg", listOf("Animation","Comedy","Action","Family","Crime")),
        MovieData("Deep Water", "Vic and Melinda Van Allen are a couple in the small town of Little Wesley. Their loveless marriage is held together only by a precarious arrangement whereby, in order to avoid the messiness of divorce, Melinda is allowed to take any number of lovers as long as she does not desert her family.", "https://image.tmdb.org/t/p/w500/6yRMyWwjuhKg6IU66uiZIGhaSc8.jpg", listOf("Drama","Mystery","Thriller")),
        MovieData("The Matrix Resurrections", "Plagued by strange memories, Neos life takes an unexpected turn when he finds himself back inside the Matrix.", "https://image.tmdb.org/t/p/w500/8c4a8kE7PizaGQQnditMmI1xbRp.jpg", listOf("Science Fiction","Action","Adventure")),
        MovieData("Ghostbusters: Afterlife", "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.", "https://image.tmdb.org/t/p/w500/sg4xJaufDiQl7caFEskBtQXfD4x.jpg", listOf("Fantasy","Comedy","Adventure")),
        MovieData("The Boss Baby: Family Business", "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.", "https://image.tmdb.org/t/p/w500/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg", listOf("Animation","Comedy","Adventure","Family")),
        MovieData("Pursuit", "Detective Breslin crosses paths with Calloway, a ruthless hacker desperate to find his wife, who has been kidnapped by a drug cartel. When Calloway escapes police custody, Breslin joins forces with a no-nonsense female cop to reclaim his prisoner. But is Calloway’s crime-boss father somehow involved in this explosive situation?", "https://image.tmdb.org/t/p/w500/oUU6blOmIu155vfIgzML3ZSsDrB.jpg", listOf("Action","Crime","Thriller")),
        MovieData("Shang-Chi and the Legend of the Ten Rings", "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.", "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg", listOf("Action","Adventure","Fantasy")),
        MovieData("Uncharted", "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.", "https://image.tmdb.org/t/p/w500/sqLowacltbZLoCa4KYye64RvvdQ.jpg", listOf("Action","Adventure")),
        MovieData("Texas Chainsaw Massacre", "In this sequel, influencers looking to breathe new life into a Texas ghost town encounter Leatherface, an infamous killer who wears a mask of human skin.", "https://image.tmdb.org/t/p/w500/meRIRfADEGVo65xgPO6eZvJ0CRG.jpg", listOf("Horror","Thriller")),
        MovieData("Sonic the Hedgehog 2", "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.", "https://image.tmdb.org/t/p/w500/1j6JtMRAhdO3RaXRtiWdPL5D3SW.jpg", listOf("Action","Science Fiction","Comedy","Family")),
        MovieData("American Siege", "An ex-NYPD officer-turned-sheriff of a small rural Georgia town has to contend with a gang of thieves who have taken a wealthy doctor hostage.", "https://image.tmdb.org/t/p/w500/daeVrgyj0ue8qb3AHyU3UeCwoZz.jpg", listOf("Action","Thriller","Crime","Drama")),
        MovieData("One Shot", "An elite squad of Navy SEALs, on a covert mission to transport a prisoner off a CIA black site island prison, are trapped when insurgents attack while trying to rescue the same prisoner.", "https://image.tmdb.org/t/p/w500/3OXiTjU30gWtqxmx4BU9RVp2OTv.jpg", listOf("Action")),
        MovieData("Fate/Grand Order Final Singularity – Grand Temple of Time: Solomon", "The Chaldea Organization must deal with the Grand Temple of Solomon, the King of Magic, which has come to destroy the world.", "https://image.tmdb.org/t/p/w500/1kRgPGHmqSpKdx1dzCjzG6QoYHb.jpg", listOf("Animation","Action","Adventure","Fantasy")),
        MovieData("The 355", "A group of top female agents from American, British, Chinese, Columbian and German  government agencies are drawn together to try and stop an organization from acquiring a deadly weapon to send the world into chaos.", "https://image.tmdb.org/t/p/w500/zxizwEPE8jhpbMgrFbwCztgvh2m.jpg", listOf("Action","Thriller")),
        MovieData("Rons Gone Wrong", "In a world where walking, talking, digitally connected bots have become childrens best friends, an 11-year-old finds that his robot buddy doesnt quite work the same as the others do.", "https://image.tmdb.org/t/p/w500/7M0uwPgwvPONdFG0jk8TPK09xJU.jpg", listOf("Animation","Science Fiction","Family","Comedy")),
        MovieData("Clifford the Big Red Dog", "As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.", "https://image.tmdb.org/t/p/w500/oifhfVhUcuDjE61V5bS5dfShQrm.jpg", listOf("Family","Adventure","Comedy","Fantasy")),
        MovieData("The Seven Deadly Sins: Cursed by Light", "With the help of the Dragon Sin of Wrath Meliodas and the worst rebels in history, the Seven Deadly Sins, the Holy War, in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the Lion Sin of Pride Escanors life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.", "https://image.tmdb.org/t/p/w500/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg", listOf("Animation","Fantasy")),
        MovieData("The Weekend Away", "When her best friend vanishes during a girls trip to Croatia, Beth races to figure out what happened. But each clue yields another unsettling deception.", "https://image.tmdb.org/t/p/w500/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg", listOf("Thriller","Mystery")),
        MovieData("Tom and Jerry: Cowboy Up!", "This time, the rivals team up to help a cowgirl and her brother save their homestead from a greedy land-grabber, and they’re going to need some help! Jerry’s three precocious nephews are all ready for action, and Tom is rounding up a posse of prairie dogs. But can a ragtag band of varmints defeat a deceitful desperado determined to deceive a damsel in distress? No matter what happens with Tom and Jerry in the saddle, it’ll be a rootin’ tootin’ good time!", "https://image.tmdb.org/t/p/w500/muIaHotSaSUQr0KZCIJOYQEe7y2.jpg", listOf("Animation","Comedy","Family","Western")),
        MovieData("The House", "Across different eras, a poor family, an anxious developer and a fed-up landlady become tied to the same mysterious house in this animated dark comedy.", "https://image.tmdb.org/t/p/w500/iZjMFSKCrleKolC1gYcz5Rs8bk1.jpg", listOf("Animation","Drama","Comedy","Horror")),
        MovieData("Chernobyl: Abyss", "The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.", "https://image.tmdb.org/t/p/w500/AmJLuHjxPdIJO6vmymeWADG6jK5.jpg", listOf("Drama","History","Adventure")),
        MovieData("Marry Me", "Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she decides to marry Charlie, a stranger in the crowd, instead.", "https://image.tmdb.org/t/p/w500/ko1JVbGj4bT8IhCWqjBQ6ZtF2t.jpg", listOf("Romance","Comedy","Music")),
        MovieData("The Hunting", "When a mysterious animal attack leaves a mutilated body in the forest, a conservative small town detective must enlist the help of an eager wildlife specialist to uncover the dark and disturbing truth that threatens the town.", "https://image.tmdb.org/t/p/w500/kvhrltQIRp1u84ao9uj52YPaWNY.jpg", listOf("Horror")),
        MovieData("The Simpsons in Plusaversary", "The Simpsons host a Disney+ Day party and everyone is on the list… except Homer. With friends from across the service and music fit for a Disney Princess, Plusaversary is Springfields event of the year.", "https://image.tmdb.org/t/p/w500/p5jzbffrXuBTjsiwrQ3aOMTrvCj.jpg", listOf("Animation","Comedy","Fantasy")),
        MovieData("Through My Window", "Raquels longtime crush on her next-door neighbor turns into something more when he starts developing feelings for her, despite his familys objections.", "https://image.tmdb.org/t/p/w500/6gg7fvKc1ZxP9yCczweSxIGYp4S.jpg", listOf("Romance","Drama")),
        MovieData("Luca", "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.", "https://image.tmdb.org/t/p/w500/jTswp6KyDYKtvC52GbHagrZbGvD.jpg", listOf("Animation","Comedy","Family","Fantasy")),
        MovieData("Free Guy", "undefined", "https://image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg", listOf("Comedy","Action","Adventure","Science Fiction")),
        MovieData("Save The Trees", "In the forests of the Pyrenees, there are still people who tell stories of trees... of fantastic beings with powers beyond our imagination. And with those trees, from the very moment in which their seeds sprout, a pixie becomes their inseparable companion.", "https://image.tmdb.org/t/p/w500/hdzUP6mV5VlSWVffA4Y18k4LK62.jpg", listOf("Animation")),
        MovieData("Brazen", "Mystery writer Grace Miller has killer instincts when it comes to motive - and shell need every bit of expertise to help solve her sisters murder.", "https://image.tmdb.org/t/p/w500/7e4n1GfC9iky9VQzH3cDQz9wYpO.jpg", listOf("Thriller","Mystery","Drama")),
        MovieData("West Side Story", "Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.", "https://image.tmdb.org/t/p/w500/yfz3IUoYYSY32tkb97HlUBGFsnh.jpg", listOf("Drama","Romance","Crime")),
        MovieData("Mortal Kombat", "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsungs best warrior, Sub-Zero, seeks out and trains with Earths greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.", "https://image.tmdb.org/t/p/w500/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg", listOf("Action","Fantasy","Adventure")),
        MovieData("Dune", "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planets exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanitys greatest potential-only those who can conquer their fear will survive.", "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", listOf("Science Fiction","Adventure")),
        MovieData("Jackass Forever", "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.", "https://image.tmdb.org/t/p/w500/ugIdyvtAzHWOguD91UjHKoAvfum.jpg", listOf("Comedy","Documentary","Action")),
        MovieData("The Suicide Squad", "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.", "https://image.tmdb.org/t/p/w500/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg", listOf("Action","Adventure","Fantasy")),
        MovieData("PAW Patrol: The Movie", "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.", "https://image.tmdb.org/t/p/w500/ic0intvXZSfBlYPIvWXpU1ivUCO.jpg", listOf("Animation","Family","Adventure","Comedy")),
        MovieData("Mother/Android", "Georgia and her boyfriend Sam go on a treacherous journey to escape their country, which is caught in an unexpected war with artificial intelligence. Days away from the arrival of their first child, the couple must face No Man’s Land—a stronghold of the android uprising—in hopes of reaching safety before giving birth.", "https://image.tmdb.org/t/p/w500/rO3nV9d1wzHEWsC7xgwxotjZQpM.jpg", listOf("Science Fiction","Thriller")),
        MovieData("F9", "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver theyve ever encountered: his forsaken brother.", "https://image.tmdb.org/t/p/w500/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg", listOf("Action","Crime","Thriller","Adventure")),
        MovieData("Sonic the Hedgehog", "undefined", "https://image.tmdb.org/t/p/w500/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg", listOf("Action","Science Fiction","Comedy","Family")),
        MovieData("Zack Snyders Justice League", "Determined to ensure Supermans ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.", "https://image.tmdb.org/t/p/w500/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg", listOf("Action","Adventure","Fantasy","Science Fiction")),
        MovieData("Queen of Spades", "According to legend, an ominous entity known as the Queen of Spades can be summoned by performing an ancient ritual. Four teenagers summon the Queen of Spades, but they could never imagine the horrors that await them.", "https://image.tmdb.org/t/p/w500/4IKBzVBPLXu9p5cfEfdJjHdlafV.jpg", listOf("Horror")),
        MovieData("The Last Warrior: Root of Evil", "Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.", "https://image.tmdb.org/t/p/w500/4qE7mvUYGY5epfcgeJpM6EfHgq5.jpg", listOf("Fantasy","Adventure","Comedy")),
        MovieData("The Pirates: The Last Royal Treasure", "A gutsy crew of Joseon pirates and bandits battle stormy waters, puzzling clues and militant rivals in search of royal gold lost at sea.", "https://image.tmdb.org/t/p/w500/50UQeTrUM7ErXzkvqCsV6EXcM3g.jpg", listOf("Action","Adventure","Comedy","History")),
        MovieData("Cruella", "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.", "https://image.tmdb.org/t/p/w500/wToO8opxkGwKgSfJ1JK8tGvkG6U.jpg", listOf("Comedy","Crime")),
        MovieData("Diary of a Wimpy Kid", "Greg Heffley is a scrawny but ambitious kid with an active imagination and big plans to be rich and famous – he just has to survive middle school first.", "https://image.tmdb.org/t/p/w500/obg6lWuNaZkoSlwrVG4VVk4SmT.jpg", listOf("Animation","Comedy","Family")),
        MovieData("Jujutsu Kaisen 0", "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and wont leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?", "https://image.tmdb.org/t/p/w500/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg", listOf("Animation","Action","Adventure","Mystery")),
        MovieData("Curious George: Cape Ahoy", "With help from a local fisherman, his niece and an adorable baby seal, George embarks on a quest in search of the long-lost shipwreck of legendary sea captain Trumpet Tooter.", "https://image.tmdb.org/t/p/w500/xHvEiU3Ja1xiGt9oq2pu0huk5m3.jpg", listOf("Animation","Adventure","Comedy")),
        MovieData("Avengers: Infinity War", "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.", "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg", listOf("Adventure","Action","Science Fiction")),
        MovieData("Rescued by Ruby", "Chasing his dream to join an elite K-9 unit, a state trooper partners with a fellow underdog: clever but naughty shelter pup Ruby. Based on a true story.", "https://image.tmdb.org/t/p/w500/tPlJEodEn0SSV4avo8KSawtlTlN.jpg", listOf("Family","Drama")),
        MovieData("No Time to Die", "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.", "https://image.tmdb.org/t/p/w500/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg", listOf("Adventure","Action","Thriller")),
        MovieData("Against the Ice", "In 1909, two explorers fight to survive after theyre left behind while on a Denmark expedition in ice-covered Greenland.", "https://image.tmdb.org/t/p/w500/6FSGYvPEhIx3ThOikGqHmKxeyNN.jpg", listOf("Adventure","History","Drama")),
        MovieData("After We Fell", "Just as Tessas life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that shes been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.", "https://image.tmdb.org/t/p/w500/dU4HfnTEJDf9KvxGS9hgO7BVeju.jpg", listOf("Romance","Drama")),
        MovieData("Dangerous", "A reformed sociopath heads to a remote island after the death of his brother. Soon after his arrival, the island falls under siege from a deadly gang of mercenaries, and when he discovers their role in his brother’s demise, he sets out on a relentless quest for vengeance.", "https://image.tmdb.org/t/p/w500/vTtkQGC7qKlSRQJZYtAWAmYdH0A.jpg", listOf("Action","Thriller")),
        MovieData("Finch", "On a post-apocalyptic Earth, a robot, built to protect the life of his dying creators beloved dog, learns about life, love, friendship, and what it means to be human.", "https://image.tmdb.org/t/p/w500/jKuDyqx7jrjiR9cDzB5pxzhJAdv.jpg", listOf("Science Fiction","Drama","Adventure")),
        MovieData("The Grandmother", "A Paris model must return to Madrid where her grandmother, who raised her, has had a stroke. But spending just a few days with this relative turns into an unexpected nightmare.", "https://image.tmdb.org/t/p/w500/kwW0Dl0pl50Uq1MHuWuIwTehjsm.jpg", listOf("Horror")),
        MovieData("Black Widow", "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.", "https://image.tmdb.org/t/p/w500/ytnhzdwtj0YfC5NVWrrPRGSGZb7.jpg", listOf("Action","Adventure","Science Fiction")),
        MovieData("Avatar", "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.", "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg", listOf("Action","Adventure","Fantasy","Science Fiction")),
        MovieData("Deathstroke: Knights & Dragons - The Movie", "The assassin Deathstroke tries to save his family from the wrath of H.I.V.E. and the murderous Jackal.", "https://image.tmdb.org/t/p/w500/vFIHbiy55smzi50RmF8LQjmpGcx.jpg", listOf("Animation","Action","Adventure","Science Fiction")),
        MovieData("Godzilla vs. Kong", "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.", "https://image.tmdb.org/t/p/w500/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg", listOf("Action","Fantasy","Science Fiction")),
        MovieData("Cheaper by the Dozen", "This remake of the beloved classic follows the raucous exploits of a blended family of 12, the Bakers, as they navigate a hectic home life while simultaneously managing their family business.", "https://image.tmdb.org/t/p/w500/qNRsouZh5zmhaE3n4QpLDXzy1gQ.jpg", listOf("Family","Comedy")),
        MovieData("Dont Breathe 2", "The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.", "https://image.tmdb.org/t/p/w500/r7HEBkkRN93d3eFBZgPJfRaob5p.jpg", listOf("Thriller","Horror")),
        MovieData("Sooryavanshi", "A fearless, faithful albeit slightly forgetful Mumbai cop, Veer Sooryavanshi, the chief of the Anti-Terrorism Squad in India pulls out all the stops and stunts to thwart a major conspiracy to attack his city.", "https://image.tmdb.org/t/p/w500/8p3mhjyLjHKtaAv8tFKfvEBtir0.jpg", listOf("Action","Crime","Thriller")),
        MovieData("Mobile Suit Gundam Hathaway", "After Chars rebellion, Hathaway Noa leads an insurgency against Earth Federation, but meeting an enemy officer and a mysterious woman alters his fate.", "https://image.tmdb.org/t/p/w500/6gw8onh4FKsruBA7Oouv01EFxzn.jpg", listOf("Animation","Action","Drama","Science Fiction")),
        MovieData("Raya and the Last Dragon", "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.", "https://image.tmdb.org/t/p/w500/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg", listOf("Family","Fantasy","Animation","Action","Adventure")),
        MovieData("Tyler Perrys A Madea Homecoming", "Madeas back - hallelujer! And shes not putting up with any nonsense as family drama erupts at her great-grandsons college graduation celebration.", "https://image.tmdb.org/t/p/w500/vzX5GNRTXsAltdU1tfASmZbzYmv.jpg", listOf("Comedy")),
        MovieData("Miraculous World: Shanghai – The Legend of Ladydragon", "On school break, Marinette heads to Shanghai to meet Adrien. But after arriving, Marinette loses all her stuff, including the Miraculous that allows her to turn into Ladybug!", "https://image.tmdb.org/t/p/w500/qQ0VKsGRQ2ofAmswGNzZnvC1xPE.jpg", listOf("Animation","Comedy","Family","Adventure")),
        MovieData("Black Crab", "To end an apocalyptic war and save her daughter, a reluctant soldier embarks on a desperate mission to cross a frozen sea carrying a top-secret cargo.", "https://image.tmdb.org/t/p/w500/mcIYHZYwUbvhvUt8Lb5nENJ7AlX.jpg", listOf("Action","Thriller")),
        MovieData("The Amazing Spider-Man", "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his fathers former partner. As Spider-Man is set on a collision course with Connors alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.", "https://image.tmdb.org/t/p/w500/fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg", listOf("Action","Adventure","Fantasy")),
        MovieData("Jungle Cruise", "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.", "https://image.tmdb.org/t/p/w500/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg", listOf("Action","Adventure","Comedy","Fantasy")),
        MovieData("The Last Duel", "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.", "https://image.tmdb.org/t/p/w500/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg", listOf("Action","Drama","History"))
    )
}

private fun getDraftMovie(rottenTomatoesSystem: RottenTomatoesSystem, movieData: MovieData): DraftMovie {
    val categories = movieData.categories.map { c -> rottenTomatoesSystem.categories.find { it.name == c }!! }.toMutableList()
    return DraftMovie(movieData.title, movieData.description, movieData.poster, categories)
}

private fun addRelatedMovies(rottenTomatoesSystem: RottenTomatoesSystem) {
    rottenTomatoesSystem.movies.forEach {
        it.relatedContent = getRandomIndexes(5).map { index -> rottenTomatoesSystem.movies[index] }.toMutableList()
    }
}

// Users

private fun addUsers(rottenTomatoesSystem: RottenTomatoesSystem) {
    rottenTomatoesSystem.addUser(DraftUser("jania", "https://robohash.org/eumutvoluptatem.jpg?size=50x50&set=set1", "jania@gmail.com", "jania"))
    rottenTomatoesSystem.addUser(DraftUser("tiebold", "https://robohash.org/eumquoasperiores.png?size=50x50&set=set1", "tiebold@gmail.com", "tiebold"))
    rottenTomatoesSystem.addUser(DraftUser("corella", "https://robohash.org/essedebitisneque.jpg?size=50x50&set=set1", "corella@gmail.com", "corella"))
    rottenTomatoesSystem.addUser(DraftUser("curry", "https://robohash.org/quidempariaturquaerat.png?size=50x50&set=set1", "curry@gmail.com", "curry"))
    rottenTomatoesSystem.addUser(DraftUser("berny", "https://robohash.org/sitquisat.png?size=50x50&set=set1", "berny@gmail.com", "berny"))
    rottenTomatoesSystem.addUser(DraftUser("chip", "https://robohash.org/aconsequatureos.png?size=50x50&set=set1", "chip@gmail.com", "chip"))
    rottenTomatoesSystem.addUser(DraftUser("sandie", "https://robohash.org/praesentiumvoluptatibuscommodi.jpg?size=50x50&set=set1", "sandie@gmail.com", "sandie"))
    rottenTomatoesSystem.addUser(DraftUser("nye", "https://robohash.org/adipisciinillo.png?size=50x50&set=set1", "nye@gmail.com", "nye"))
    rottenTomatoesSystem.addUser(DraftUser("tallia", "https://robohash.org/nonharumautem.png?size=50x50&set=set1", "tallia@gmail.com", "tallia"))
    rottenTomatoesSystem.addUser(DraftUser("ashlen", "https://robohash.org/corruptimaximetotam.png?size=50x50&set=set1", "ashlen@gmail.com", "ashlen"))
    rottenTomatoesSystem.addUser(DraftUser("woodman", "https://robohash.org/temporedolorumunde.bmp?size=50x50&set=set1", "woodman@gmail.com", "woodman"))
    rottenTomatoesSystem.addUser(DraftUser("kacie", "https://robohash.org/veritatisiurevoluptatem.jpg?size=50x50&set=set1", "kacie@gmail.com", "kacie"))
    rottenTomatoesSystem.addUser(DraftUser("des", "https://robohash.org/omnispossimusprovident.png?size=50x50&set=set1", "des@gmail.com", "des"))
    rottenTomatoesSystem.addUser(DraftUser("adrienne", "https://robohash.org/facilisnobisdignissimos.png?size=50x50&set=set1", "adrienne@gmail.com", "adrienne"))
    rottenTomatoesSystem.addUser(DraftUser("rebecka", "https://robohash.org/voluptatedoloremut.bmp?size=50x50&set=set1", "rebecka@gmail.com", "rebecka"))
    rottenTomatoesSystem.addUser(DraftUser("emilia", "https://robohash.org/aperiaminmolestiae.bmp?size=50x50&set=set1", "emilia@gmail.com", "emilia"))
    rottenTomatoesSystem.addUser(DraftUser("mallorie", "https://robohash.org/quiquasinihil.jpg?size=50x50&set=set1", "mallorie@gmail.com", "mallorie"))
    rottenTomatoesSystem.addUser(DraftUser("octavia", "https://robohash.org/quidebitisquis.bmp?size=50x50&set=set1", "octavia@gmail.com", "octavia"))
    rottenTomatoesSystem.addUser(DraftUser("palmer", "https://robohash.org/nemosequilaudantium.jpg?size=50x50&set=set1", "palmer@gmail.com", "palmer"))
    rottenTomatoesSystem.addUser(DraftUser("nicko", "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1", "nicko@gmail.com", "nicko"))
    rottenTomatoesSystem.addUser(DraftUser("juan", "https://robohash.org/facilisnobisdignissimos.png?size=50x50&set=set1", "juan@gmail.com", "juan"))
    rottenTomatoesSystem.addUser(DraftUser("rodrigo", "https://robohash.org/voluptatedoloremut.bmp?size=50x50&set=set1", "rodrigo@gmail.com", "rodrigo"))
    rottenTomatoesSystem.addUser(DraftUser("jesus", "https://robohash.org/aperiaminmolestiae.bmp?size=50x50&set=set1", "jesus@gmail.com", "jesus"))
    rottenTomatoesSystem.addUser(DraftUser("pepe", "https://robohash.org/quiquasinihil.jpg?size=50x50&set=set1", "pepe@gmail.com", "pepe"))
    rottenTomatoesSystem.addUser(DraftUser("martin", "https://robohash.org/quidebitisquis.bmp?size=50x50&set=set1", "martin@gmail.com", "martin"))
    rottenTomatoesSystem.addUser(DraftUser("ines", "https://robohash.org/nemosequilaudantium.jpg?size=50x50&set=set1", "ines@gmail.com", "ines"))
    rottenTomatoesSystem.addUser(DraftUser("flor", "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1", "flor@gmail.com", "flor"))
    rottenTomatoesSystem.addUser(DraftUser("a", "https://robohash.org/uttemporibusrerum.png?size=50x50&set=set1", "a@gmail.com", "a"))
    rottenTomatoesSystem.addUser(DraftUser("b", "https://robohash.org/corruptimaximetotam.png?size=50x50&set=set1", "b@gmail.com", "b"))
    rottenTomatoesSystem.addUser(DraftUser("c", "https://robohash.org/quidempariaturquaerat.png?size=50x50&set=set1", "c@gmail.com", "c"))
}

// Reviews

private fun addReview(rottenTomatoesSystem: RottenTomatoesSystem) {
    rottenTomatoesSystem.users.forEach { user ->
        val moviesIds = getRandomIndexes(15).map { index -> rottenTomatoesSystem.movies[index].id }
        moviesIds.forEach { movieId ->
            val textIndex = getRandomIndexes(1, 15)[0]
            rottenTomatoesSystem.addReview(DraftReview(user.id, movieId, reviewsText[textIndex], getRandomIndexes(1, 6)[0]))
        }
    }
}
